// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5LbKeFyBNaenm0B9eoS9vTwJMPH_rfo',
    appId: '1:974969582396:web:4f0c4e34154d9dd771e439',
    messagingSenderId: '974969582396',
    projectId: 'e-commerce-flutter-79f30',
    authDomain: 'e-commerce-flutter-79f30.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-79f30.appspot.com',
    measurementId: 'G-MZQPP7F4RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapqh1BsXWeNq8lOmZRyVNVtVkFhDZ5WI',
    appId: '1:974969582396:android:46fa5b279b81607471e439',
    messagingSenderId: '974969582396',
    projectId: 'e-commerce-flutter-79f30',
    storageBucket: 'e-commerce-flutter-79f30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKGV2ksufvyPCsZ2wG4thHTOt9FHLONkI',
    appId: '1:974969582396:ios:253592cbec0af78071e439',
    messagingSenderId: '974969582396',
    projectId: 'e-commerce-flutter-79f30',
    storageBucket: 'e-commerce-flutter-79f30.appspot.com',
    iosBundleId: 'com.example.eCommerence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKGV2ksufvyPCsZ2wG4thHTOt9FHLONkI',
    appId: '1:974969582396:ios:a2a8e0c9cf4342bc71e439',
    messagingSenderId: '974969582396',
    projectId: 'e-commerce-flutter-79f30',
    storageBucket: 'e-commerce-flutter-79f30.appspot.com',
    iosBundleId: 'com.example.eCommerence.RunnerTests',
  );
}
